<div class="top-bar">
  
  <div class="container">
  <div class="col-sm-4 col-md-4 log-col">
  <?php echo $this->getChildHtml("logo"); ?>
  
  </div>
  
  <div class="col-sm-8 col-md-5 top-right hidden-xs ">
  	<span class="top-search">   
  		<div class="search">
  <?php echo $this->getChildHtml("topSearch"); ?>
        </div>
    </span>

   <span class="phone-bar"><i class="fa fa-phone"></i> <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-header-wrapper')->toHtml(); ?></span>
  </div>
  
  </div>
</div>
